### ISSUE TITLE
Error: "attempt to index local 'cjson' (a boolean value)"

### ISSUE THREAD

**Issue by rogersguedes** [bungle/lua-resty-prettycjson#6]
Hello Aapo,
I'm get the following error when running the sample code contained in the main README of this repo:

```
lua: lua_modules/share/lua/5.1/resty\prettycjson.lua:2: attempt to index local 'cjson' (a boolean value)
stack traceback:
        lua_modules/share/lua/5.1/resty\prettycjson.lua:2: in main chunk
        [C]: in function 'require'
        wtf.lua:3: in main chunk
        [C]: ?
```

**Comment by bungle** [comment]
Hi @rogersguedes,

Have you installed `cJSON`, e.g. `luarocks install lua-cjson`?  It somehow feels that:

```lua
print(type(require("cjson.safe")))
```

returns `nil`?

**Comment by rogersguedes** [comment]
I had not installed cJSON. I thought luarocks would manage dependencies by it self.
So, after knowing this, I just had installed it. But, as You said above, it is returning nil and a error message, as follows: 
```
root@ROOT-PC C:\sandBox\classesL2lua
> luarocks install --tree lua_modules lua-cjson
Installing https://luarocks.org/lua-cjson-2.1.0-1.src.rock
C:\MinGW\bin\gcc.exe -O2 -c -o lua_cjson.o -IC:/opt/lua-5.1/include lua_cjson.c -DDISABLE_INVALID_NUMBERS
In file included from lua_cjson.c:47:0:
fpconv.h:15:20: warning: inline function 'fpconv_init' declared but never defined
 extern inline void fpconv_init();
                    ^~~~~~~~~~~
C:\MinGW\bin\gcc.exe -O2 -c -o strbuf.o -IC:/opt/lua-5.1/include strbuf.c -DDISABLE_INVALID_NUMBERS
C:\MinGW\bin\gcc.exe -O2 -c -o fpconv.o -IC:/opt/lua-5.1/include fpconv.c -DDISABLE_INVALID_NUMBERS
C:\MinGW\bin\gcc.exe -shared -o cjson.dll lua_cjson.o strbuf.o fpconv.o C:/opt/lua-5.1/bin/lua51.dll -lm
lua-cjson 2.1.0-1 is now installed in C:/sandBox/classesL2lua/lua_modules (license: MIT)


root@ROOT-PC C:\sandBox\classesL2lua
> luarocks install --tree lua_modules lua-resty-prettycjson
Installing https://luarocks.org/lua-resty-prettycjson-1.6-1.src.rock
lua-resty-prettycjson 1.6-1 is now installed in C:/sandBox/classesL2lua/lua_modules (license: BSD)


root@ROOT-PC C:\sandBox\classesL2lua
> luarocks list --tree lua_modules

Installed rocks:
----------------

csv
   1-1 (installed) - C:/sandBox/classesL2lua/lua_modules/lib/luarocks/rocks

json4lua
   0.9.30-1 (installed) - C:/sandBox/classesL2lua/lua_modules/lib/luarocks/rocks

lua-cjson
   2.1.0-1 (installed) - C:/sandBox/classesL2lua/lua_modules/lib/luarocks/rocks

lua-resty-prettycjson
   1.6-1 (installed) - C:/sandBox/classesL2lua/lua_modules/lib/luarocks/rocks


root@ROOT-PC C:\sandBox\classesL2lua
> lua sample.lua
nil     Lua cJSON encoder not found

root@ROOT-PC C:\sandBox\classesL2lua
>
```

Follow the used sample code:

```
version = _VERSION:match("%d+%.%d+")
package.path = 'lua_modules/share/lua/' .. version .. '/?.lua;lua_modules/share/lua/' .. version .. '/?/init.lua;' .. package.path
package.cpath = 'lua_modules/lib/lua/' .. version .. '/?.so;' .. package.cpath

local pretty = require "resty.prettycjson"

print(pretty({
    key1 = "data",
    key2 = 27,
    key3 = {
        key3_1 = "something",
        key3_2 = "something else"
    },
    key4 = {
        "item1",
        "item2"
    },
    key5 = {},
    key5 = {{''}, {'',''}, {{},{}}},
    key6 = { '' },
    key7 = {{{{ test = "value", {{{{{{}}},{{},{},{}},{},{}}}}}}}}
}))
```
Thank you in advance. :)

**Comment by bungle** [comment]
@rogersguedes 

what is inside your:
```
'lua_modules/lib/lua/' .. version
```

Is the `cjson.so` there?

**Comment by rogersguedes** [comment]
My lua version is "5.1", so the `version` holds this string.
I take this code bellow [1] from [this tutorial](http://leafo.net/guides/customizing-the-luarocks-tree.html), because I would like to places the modules inside the 'project' folder, as we do in composer (PHP) and npm (Node.JS), with a non global way.
```
[1]
version = _VERSION:match("%d+%.%d+")
package.path = 'lua_modules/share/lua/' .. version .. '/?.lua;lua_modules/share/lua/' .. version .. '/?/init.lua;' .. package.path
package.cpath = 'lua_modules/lib/lua/' .. version .. '/?.so;' .. package.cpath
```
When I get home, I will check where `cjson.so` placed at.

ThankYou a lot 👍

**Comment by rogersguedes** [comment]
Hey, I came back home 8)
Inside my `lua_modules\lib\lua\5.1` folder there is a DLL file named `cjson.dll`.

If you want, I can give you a TeamViewer session while I'm in my PC. We just should schedule a good time for both.

**Comment by bungle** [comment]
How about:
```
package.cpath = 'lua_modules/lib/lua/' .. version .. '/?.dll;' .. 'lua_modules/lib/lua/' .. version .. '/?.so;' .. package.cpath
```

See I added `.dll`, or copy that `cjson.dll` to `cjson.so`. (also just in case, try to provide full path, if the above doesn't help).

**Comment by rogersguedes** [comment]
Yeees, It worked!
Hooo man, how idiot I was. Sorry for this mess.
Thank you a lot! :)

**Comment by rogersguedes** [comment]
But I still having a little question: 
Why did not the `luarocks install --tree lua_modules lua-resty-prettycjson`  installed `lua-cjson`? By the way, one of the goals of package managers is to deal with dependencies.

**Comment by bungle** [comment]
Because it is not a dependency:
https://github.com/bungle/lua-resty-prettycjson/blob/master/lua-resty-prettycjson-dev-1.rockspec#L13-L15

You can pass your own JSON encoder as argument:
https://github.com/bungle/lua-resty-prettycjson/blob/master/lib/resty/prettycjson.lua#L6

There are several Lua cJSONs. E.g. OpenResty comes with one built-in. So it is a bit unintuitive to add the dependency. YMMV. I think it is good enough as is.
